version: '3.8'

services:
  enphase-monitor:
    build: .
    container_name: enphase-monitor
    ports:
      - "3000:3000"
    volumes:
      - ./db/:/usr/src/app/db/
    env_file:
      - .env
    restart: unless-stopped
